// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“CusBasedataOutputDto.cs”的分部类“public partial class CusBasedataOutputDto”}添加属性
// </auto-generated>
//
//  <copyright file="CusBasedataOutputDto.generated.cs" company="teng.kun">
//      teng.kun
//  </copyright>
//  <site>http://teng.kun</site>
//  <last-editor>teng.kun</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;
using OSharp.Mapping;

using teng.kun.BaseModule.Entities;

namespace teng.kun.BaseModule.Dtos
{
    /// <summary>
    /// 输入DTO：客户基础数据信息
    /// </summary>
    [MapFrom(typeof(CusBasedata))]
    [Description("客户基础数据信息")]
    public partial class CusBasedataOutputDto : IOutputDto
    {
        /// <summary>
        /// 初始化一个<see cref="CusBasedataOutputDto"/>类型的新实例
        /// </summary>
        public CusBasedataOutputDto()
        { }

        /// <summary>
        /// 初始化一个<see cref="CusBasedataOutputDto"/>类型的新实例
        /// </summary>
        public CusBasedataOutputDto(CusBasedata entity)
        {
            Id = entity.Id;
            CusId = entity.CusId;
            CusName = entity.CusName;
            CusPhone = entity.CusPhone;
            CusComStartTime = entity.CusComStartTime;
            CusComEndTime = entity.CusComEndTime;
            CusState = entity.CusState;
            CusRemark = entity.CusRemark;
            CreatedTime = entity.CreatedTime;
        }

        /// <summary>
        /// 获取或设置 编号
        /// </summary>
        [DisplayName("编号")]
        public int Id { get; set; }

        /// <summary>
        /// 获取或设置 客户编码
        /// </summary>
        [DisplayName("客户编码")]
        public string CusId { get; set; }

        /// <summary>
        /// 获取或设置 名称
        /// </summary>
        [DisplayName("名称")]
        public string CusName { get; set; }

        /// <summary>
        /// 获取或设置 联系方式
        /// </summary>
        [DisplayName("联系方式")]
        public string CusPhone { get; set; }

        /// <summary>
        /// 获取或设置 合作开始时间
        /// </summary>
        [DisplayName("合作开始时间")]
        public DateTime CusComStartTime { get; set; }

        /// <summary>
        /// 获取或设置 合作结束时间
        /// </summary>
        [DisplayName("合作结束时间")]
        public DateTime CusComEndTime { get; set; }

        /// <summary>
        /// 获取或设置 合作状态
        /// </summary>
        [DisplayName("合作状态")]
        public bool CusState { get; set; }

        /// <summary>
        /// 获取或设置 备注
        /// </summary>
        [DisplayName("备注")]
        public string CusRemark { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

    }
}
