// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“EmpBasedataOutputDto.cs”的分部类“public partial class EmpBasedataOutputDto”}添加属性
// </auto-generated>
//
//  <copyright file="EmpBasedataOutputDto.generated.cs" company="teng.kun">
//      teng.kun
//  </copyright>
//  <site>http://teng.kun</site>
//  <last-editor>teng.kun</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;
using OSharp.Mapping;

using teng.kun.BaseModule.Entities;

namespace teng.kun.BaseModule.Dtos
{
    /// <summary>
    /// 输入DTO：员工基础数据信息
    /// </summary>
    [MapFrom(typeof(EmpBasedata))]
    [Description("员工基础数据信息")]
    public partial class EmpBasedataOutputDto : IOutputDto
    {
        /// <summary>
        /// 初始化一个<see cref="EmpBasedataOutputDto"/>类型的新实例
        /// </summary>
        public EmpBasedataOutputDto()
        { }

        /// <summary>
        /// 初始化一个<see cref="EmpBasedataOutputDto"/>类型的新实例
        /// </summary>
        public EmpBasedataOutputDto(EmpBasedata entity)
        {
            Id = entity.Id;
            EmpId = entity.EmpId;
            EmpName = entity.EmpName;
            EmpDep = entity.EmpDep;
            EmpPhone = entity.EmpPhone;
            EmpWorkState = entity.EmpWorkState;
            EmpFireState = entity.EmpFireState;
            EmpWorkInTime = entity.EmpWorkInTime;
            EmpWorkOutTime = entity.EmpWorkOutTime;
            EmpRemark = entity.EmpRemark;
            CreatedTime = entity.CreatedTime;
        }

        /// <summary>
        /// 获取或设置 编号
        /// </summary>
        [DisplayName("编号")]
        public int Id { get; set; }

        /// <summary>
        /// 获取或设置 员工编码
        /// </summary>
        [DisplayName("员工编码")]
        public string EmpId { get; set; }

        /// <summary>
        /// 获取或设置 姓名
        /// </summary>
        [DisplayName("姓名")]
        public string EmpName { get; set; }

        /// <summary>
        /// 获取或设置 部门
        /// </summary>
        [DisplayName("部门")]
        public string EmpDep { get; set; }

        /// <summary>
        /// 获取或设置 联系方式
        /// </summary>
        [DisplayName("联系方式")]
        public string EmpPhone { get; set; }

        /// <summary>
        /// 获取或设置 忙碌状态
        /// </summary>
        [DisplayName("忙碌状态")]
        public bool EmpWorkState { get; set; }

        /// <summary>
        /// 获取或设置 在职状态
        /// </summary>
        [DisplayName("在职状态")]
        public bool EmpFireState { get; set; }

        /// <summary>
        /// 获取或设置 入职时间
        /// </summary>
        [DisplayName("入职时间")]
        public DateTime EmpWorkInTime { get; set; }

        /// <summary>
        /// 获取或设置 离职时间
        /// </summary>
        [DisplayName("离职时间")]
        public DateTime EmpWorkOutTime { get; set; }

        /// <summary>
        /// 获取或设置 备注
        /// </summary>
        [DisplayName("备注")]
        public string EmpRemark { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

    }
}
