// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“SupBasedataOutputDto.cs”的分部类“public partial class SupBasedataOutputDto”}添加属性
// </auto-generated>
//
//  <copyright file="SupBasedataOutputDto.generated.cs" company="teng.kun">
//      teng.kun
//  </copyright>
//  <site>http://teng.kun</site>
//  <last-editor>teng.kun</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;
using OSharp.Mapping;

using teng.kun.BaseModule.Entities;

namespace teng.kun.BaseModule.Dtos
{
    /// <summary>
    /// 输入DTO：供应商基础数据信息
    /// </summary>
    [MapFrom(typeof(SupBasedata))]
    [Description("供应商基础数据信息")]
    public partial class SupBasedataOutputDto : IOutputDto
    {
        /// <summary>
        /// 初始化一个<see cref="SupBasedataOutputDto"/>类型的新实例
        /// </summary>
        public SupBasedataOutputDto()
        { }

        /// <summary>
        /// 初始化一个<see cref="SupBasedataOutputDto"/>类型的新实例
        /// </summary>
        public SupBasedataOutputDto(SupBasedata entity)
        {
            Id = entity.Id;
            SupPhone = entity.SupPhone;
            SupName = entity.SupName;
            SupId = entity.SupId;
            SupComStartTime = entity.SupComStartTime;
            SupComEndTime = entity.SupComEndTime;
            SupState = entity.SupState;
            SupRemark = entity.SupRemark;
            CreatedTime = entity.CreatedTime;
        }

        /// <summary>
        /// 获取或设置 编号
        /// </summary>
        [DisplayName("编号")]
        public int Id { get; set; }

        /// <summary>
        /// 获取或设置 联系方式
        /// </summary>
        [DisplayName("联系方式")]
        public string SupPhone { get; set; }

        /// <summary>
        /// 获取或设置 名称
        /// </summary>
        [DisplayName("名称")]
        public string SupName { get; set; }

        /// <summary>
        /// 获取或设置 供应商编码
        /// </summary>
        [DisplayName("供应商编码")]
        public string SupId { get; set; }

        /// <summary>
        /// 获取或设置 开始合作时间
        /// </summary>
        [DisplayName("开始合作时间")]
        public DateTime SupComStartTime { get; set; }

        /// <summary>
        /// 获取或设置 结束合作时间
        /// </summary>
        [DisplayName("结束合作时间")]
        public DateTime SupComEndTime { get; set; }

        /// <summary>
        /// 获取或设置 合作状态
        /// </summary>
        [DisplayName("合作状态")]
        public bool SupState { get; set; }

        /// <summary>
        /// 获取或设置 备注
        /// </summary>
        [DisplayName("备注")]
        public string SupRemark { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

    }
}
