// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，可以遵守如下规则进行扩展：
//      1.横向扩展：如需给当前实体 LeaveBp 添加方法，可新建文件“BpmServiceBase.LeaveBp.cs”的分部类“public abstract partial class BpmServiceBase”添加功能
//      2.纵向扩展：如需要重写当前实体 LeaveBp 的业务实现，可新建文件“BpmService.LeaveBp.cs”的分部类“public partial class BpmService”对现有方法进行方法重写实现
// </auto-generated>
//
//  <copyright file="BpmServiceBase.LeaveBp.generated.cs" company="teng.kun">
//      teng.kun
//  </copyright>
//  <site>http://teng.kun</site>
//  <last-editor>teng.kun</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

using OSharp.Data;
using OSharp.Dependency;
using OSharp.Extensions;
using OSharp.Mapping;

using teng.kun.Bpm.Dtos;
using teng.kun.Bpm.Entities;


namespace teng.kun.Bpm
{
    public abstract partial class BpmServiceBase
    {
        /// <summary>
        /// 获取 请假流程信息查询数据集
        /// </summary>
        public IQueryable<LeaveBp> LeaveBps
        {
            get { return LeaveBpRepository.QueryAsNoTracking(); }
        }

        /// <summary>
        /// 检查请假流程信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的请假流程信息编号</param>
        /// <returns>请假流程信息是否存在</returns>
        public virtual Task<bool> CheckLeaveBpExists(Expression<Func<LeaveBp, bool>> predicate, int id = default(int))
        {
            return LeaveBpRepository.CheckExistsAsync(predicate, id);
        }
        
        /// <summary>
        /// 添加请假流程信息
        /// </summary>
        /// <param name="dtos">要添加的请假流程信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        public virtual Task<OperationResult> CreateLeaveBps(params LeaveBpInputDto[] dtos)
        {
            Check.Validate<LeaveBpInputDto, int>(dtos, nameof(dtos));
            return LeaveBpRepository.InsertAsync(dtos);
        }
        
        /// <summary>
        /// 更新请假流程信息
        /// </summary>
        /// <param name="dtos">包含更新信息的请假流程信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        public virtual Task<OperationResult> UpdateLeaveBps(params LeaveBpInputDto[] dtos)
        {
            Check.Validate<LeaveBpInputDto, int>(dtos, nameof(dtos));
            return LeaveBpRepository.UpdateAsync(dtos);
        }
        
        /// <summary>
        /// 删除请假流程信息
        /// </summary>
        /// <param name="ids">要删除的请假流程信息编号</param>
        /// <returns>业务操作结果</returns>
        public virtual Task<OperationResult> DeleteLeaveBps(params int[] ids)
        {
            Check.NotNull(ids, nameof(ids));
            return LeaveBpRepository.DeleteAsync(ids);
        }
    }
}
