// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“Test09InputDto.cs”的分部类“public partial class Test09InputDto”}添加属性
// </auto-generated>
//
//  <copyright file="Test09InputDto.generated.cs" company="teng.kun">
//      teng.kun
//  </copyright>
//  <site>http://teng.kun</site>
//  <last-editor>teng.kun</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;
using OSharp.Mapping;

using teng.kun.OutStorManager.Entities;


namespace teng.kun.OutStorManager.Dtos
{
    /// <summary>
    /// 输入DTO：test09信息
    /// </summary>
    [MapTo(typeof(Test09))]
    [Description("test09信息")]
    public partial class Test09InputDto : IInputDto<int>
    {
        /// <summary>
        /// 获取或设置 编号
        /// </summary>
        [DisplayName("编号")]
        public int Id { get; set; }

    }
}
