//------------------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“SupBasedata.cs”的分部类“public partial class SupBasedata”}添加属性
// </auto-generated>
//
//  <copyright file="SupBasedata.generated.cs" company="teng.kun">
//      teng.kun
//  </copyright>
//  <site>http://teng.kun</site>
//  <last-editor>teng.kun</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;


namespace teng.kun.BaseModule.Entities
{
    /// <summary>
    /// 实体类：供应商基础数据信息
    /// </summary>
    [Description("供应商基础数据信息")]
    [TableNamePrefix("BaseModule")]
    public partial class SupBasedata : EntityBase<int>, ICreatedTime
    {
        /// <summary>
        /// 获取或设置 联系方式
        /// </summary>
        [DisplayName("联系方式")]
        public string SupPhone { get; set; }

        /// <summary>
        /// 获取或设置 名称
        /// </summary>
        [DisplayName("名称"), Required]
        public string SupName { get; set; }

        /// <summary>
        /// 获取或设置 供应商编码
        /// </summary>
        [DisplayName("供应商编码"), Required]
        public string SupId { get; set; }

        /// <summary>
        /// 获取或设置 开始合作时间
        /// </summary>
        [DisplayName("开始合作时间")]
        public DateTime SupComStartTime { get; set; }

        /// <summary>
        /// 获取或设置 结束合作时间
        /// </summary>
        [DisplayName("结束合作时间")]
        public DateTime SupComEndTime { get; set; }

        /// <summary>
        /// 获取或设置 合作状态
        /// </summary>
        [DisplayName("合作状态")]
        public bool SupState { get; set; }

        /// <summary>
        /// 获取或设置 备注
        /// </summary>
        [DisplayName("备注")]
        public string SupRemark { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

    }
}

