// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，可以遵守如下规则进行扩展：
//      1.横向扩展：如需给当前实体 Test09 添加方法，可新建文件“OutStorManagerServiceBase.Test09.cs”的分部类“public abstract partial class OutStorManagerServiceBase”添加功能
//      2.纵向扩展：如需要重写当前实体 Test09 的业务实现，可新建文件“OutStorManagerService.Test09.cs”的分部类“public partial class OutStorManagerService”对现有方法进行方法重写实现
// </auto-generated>
//
//  <copyright file="OutStorManagerServiceBase.Test09.generated.cs" company="teng.kun">
//      teng.kun
//  </copyright>
//  <site>http://teng.kun</site>
//  <last-editor>teng.kun</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

using OSharp.Data;
using OSharp.Dependency;
using OSharp.Extensions;
using OSharp.Mapping;

using teng.kun.OutStorManager.Dtos;
using teng.kun.OutStorManager.Entities;


namespace teng.kun.OutStorManager
{
    public abstract partial class OutStorManagerServiceBase
    {
        /// <summary>
        /// 获取 test09信息查询数据集
        /// </summary>
        public IQueryable<Test09> Test09s
        {
            get { return Test09Repository.QueryAsNoTracking(); }
        }

        /// <summary>
        /// 检查test09信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的test09信息编号</param>
        /// <returns>test09信息是否存在</returns>
        public virtual Task<bool> CheckTest09Exists(Expression<Func<Test09, bool>> predicate, int id = default(int))
        {
            return Test09Repository.CheckExistsAsync(predicate, id);
        }
        
        /// <summary>
        /// 添加test09信息
        /// </summary>
        /// <param name="dtos">要添加的test09信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        public virtual Task<OperationResult> CreateTest09s(params Test09InputDto[] dtos)
        {
            Check.Validate<Test09InputDto, int>(dtos, nameof(dtos));
            return Test09Repository.InsertAsync(dtos);
        }
        
        /// <summary>
        /// 更新test09信息
        /// </summary>
        /// <param name="dtos">包含更新信息的test09信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        public virtual Task<OperationResult> UpdateTest09s(params Test09InputDto[] dtos)
        {
            Check.Validate<Test09InputDto, int>(dtos, nameof(dtos));
            return Test09Repository.UpdateAsync(dtos);
        }
        
        /// <summary>
        /// 删除test09信息
        /// </summary>
        /// <param name="ids">要删除的test09信息编号</param>
        /// <returns>业务操作结果</returns>
        public virtual Task<OperationResult> DeleteTest09s(params int[] ids)
        {
            Check.NotNull(ids, nameof(ids));
            return Test09Repository.DeleteAsync(ids);
        }
    }
}
