// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，可以遵守如下规则进行扩展：
//      1. 横向扩展：如需给当前模块添加方法接口，可新建文件“IInStorManagerContract.cs”的分部接口“public partial interface IInStorManagerContract”添加方法，并添加相应新的分部基类 abstract partial class InStorManagerServiceBase 实现新方法
// </auto-generated>
//
//  <copyright file="IInStorManagerContract.generated.cs" company="teng.kun">
//      teng.kun
//  </copyright>
//  <site>http://teng.kun</site>
//  <last-editor>teng.kun</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

using OSharp.Data;
using OSharp.Extensions;

using teng.kun.InStorManager.Dtos;
using teng.kun.InStorManager.Entities;


namespace teng.kun.InStorManager
{
    /// <summary>
    /// 业务契约接口：入库管理模块
    /// </summary>
    public partial interface IInStorManagerContract
    {
        #region 入库信息业务

        /// <summary>
        /// 获取 入库信息查询数据集
        /// </summary>
        IQueryable<InStor> InStors { get; }

        /// <summary>
        /// 检查入库信息信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的入库信息编号</param>
        /// <returns>入库信息是否存在</returns>
        Task<bool> CheckInStorExists(Expression<Func<InStor, bool>> predicate, int id = default(int));
        
        /// <summary>
        /// 添加入库信息信息
        /// </summary>
        /// <param name="dtos">要添加的入库信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        Task<OperationResult> CreateInStors(params InStorInputDto[] dtos);
            
        /// <summary>
        /// 更新入库信息信息
        /// </summary>
        /// <param name="dtos">包含更新信息的入库信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        Task<OperationResult> UpdateInStors(params InStorInputDto[] dtos);
            
        /// <summary>
        /// 删除入库信息信息
        /// </summary>
        /// <param name="ids">要删除的入库信息编号</param>
        /// <returns>业务操作结果</returns>
        Task<OperationResult> DeleteInStors(params int[] ids);
        

        #endregion
        
    }
}
