//------------------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“LeaveBp.cs”的分部类“public partial class LeaveBp”}添加属性
// </auto-generated>
//
//  <copyright file="LeaveBp.generated.cs" company="teng.kun">
//      teng.kun
//  </copyright>
//  <site>http://teng.kun</site>
//  <last-editor>teng.kun</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;


namespace teng.kun.Bpm.Entities
{
    /// <summary>
    /// 实体类：请假流程信息
    /// </summary>
    [Description("请假流程信息")]
    [TableNamePrefix("Bpm")]
    public partial class LeaveBp : EntityBase<int>, ICreatedTime
    {
        /// <summary>
        /// 获取或设置 流程编码
        /// </summary>
        [DisplayName("流程编码"), Required]
        public string BpId { get; set; }

        /// <summary>
        /// 获取或设置 标题
        /// </summary>
        [DisplayName("标题"), Required]
        public string BpTitle { get; set; }

        /// <summary>
        /// 获取或设置 状态
        /// </summary>
        [DisplayName("状态")]
        public string BpState { get; set; }

        /// <summary>
        /// 获取或设置 发起人
        /// </summary>
        [DisplayName("发起人")]
        public string BpSponsor { get; set; }

        /// <summary>
        /// 获取或设置 上一节点
        /// </summary>
        [DisplayName("上一节点")]
        public int PrevNode { get; set; }

        /// <summary>
        /// 获取或设置 当前节点
        /// </summary>
        [DisplayName("当前节点")]
        public int CurrNode { get; set; }

        /// <summary>
        /// 获取或设置 下一节点
        /// </summary>
        [DisplayName("下一节点")]
        public int NextNode { get; set; }

        /// <summary>
        /// 获取或设置 请假开始时间
        /// </summary>
        [DisplayName("请假开始时间")]
        public DateTime LeaveStartTime { get; set; }

        /// <summary>
        /// 获取或设置 请假结束时间
        /// </summary>
        [DisplayName("请假结束时间")]
        public DateTime LeaveEndTime { get; set; }

        /// <summary>
        /// 获取或设置 请假原因
        /// </summary>
        [DisplayName("请假原因")]
        public string LeaveReason { get; set; }

        /// <summary>
        /// 获取或设置 备注
        /// </summary>
        [DisplayName("备注")]
        public string Remark { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

    }
}

